import React from 'react';
import PropTypes from 'prop-types';
import { uniqueId } from 'lodash';
import assert from 'assert';
import utils from 'utils';
import ToggleRenderer from './toggle-renderer';

import './toggle.css';

const { handleKeyEvent } = utils;

/**
 * Toggle (switch) control
 */
class Toggle extends React.Component {
  /**
   * constructor - create new Tabs
   * @param {Object} props properties passed to component
   */
  constructor(props) {
    super(props);

    assert(this.props.texts.length === 2, 'Please provide exactly 2 string for the texts prop!');

    // create a unique id if the user did not provide one
    this.id = this.props.id || uniqueId('toggle-');

    this.state = {
      value: props.value
    };

    this._handleChange = this._handleChange.bind(this);
    this._handleKeyDown = this._handleKeyDown.bind(this);
  }

  /**
   * React lifecycle method
   * {@link https://facebook.github.io/react/docs/react-component.html#componentdidupdate}
   * @return {object} JSX for this component
   */
  componentDidUpdate(prevProps) {
    if (this.props.value !== prevProps.value) {
      this.setState({ value: this.props.value });
    }
  }

  /**
   * Callback function for selection change
   * @param {object} e                The event object
   * @param {string} payload.value The new value (on/off)
   */
  _handleChange(e, { value }) {
    // call the user defined callback
    if (typeof this.props.onChange === 'function') {
      this.props.onChange(e, { value });
    }

    this.setState({ value });
  }

  /**
   * Allow users to toggle the value using ←↑→↓ arrow keys
   * @param {number} e.keyCode - The event object keyboard character code
   */
  _handleKeyDown({ keyCode }) {
    handleKeyEvent(keyCode, {
      left: () => this.setState({ value: true }),
      up: () => this.setState({ value: true }),
      right: () => this.setState({ value: false }),
      down: () => this.setState({ value: false })
    });
  }

  /**
   * React lifecycle method
   * {@link https://facebook.github.io/react/docs/react-component.html#render}
   * @return {object} JSX for this component
   */
  render() {
    return (
      <ToggleRenderer
        disabled={this.props.disabled}
        id={this.id}
        label={this.props.label}
        onChange={this._handleChange}
        onKeyDown={this._handleKeyDown}
        texts={this.props.texts}
        theme={this.props.theme}
        type={this.props.type}
        value={this.state.value} />
    );
  }
}

Toggle.defaultProps = {
  disabled: false,
  id: null,
  label: '',
  onChange: null,
  texts: ['ON', 'OFF'],
  theme: 'dark',
  type: 'regular',
  value: true
};

Toggle.propTypes = {
  /**
   * Toggle whether component is disabled
   */
  disabled: PropTypes.bool,
  /**
   * A unique is for the toggle (autogenerated if not provided)
   */
  id: PropTypes.string,
  /**
   * Label for the toggle
   */
  label: PropTypes.string,
  /**
   * Callback when the toggle changes value (params: event, payload: { value })
   */
  onChange: PropTypes.func,
  /**
   * Array of 2 strings to display in the toggle
   */
  texts: PropTypes.arrayOf(PropTypes.string),
  /**
   * Theme name for component
   */
  theme: PropTypes.oneOf(['dark', 'light']),
  /**
   * Sets the label type
   */
  type: PropTypes.oneOf(['regular', 'bold']),
  /**
   * Initial value
   */
  value: PropTypes.bool
};

export default Toggle;
